### ISSUE TITLE
[BUG]System.InvalidCastException when using MSNotificationHubMessage for iOS

### ISSUE THREAD

**Issue by RST90** [Azure/azure-notificationhubs-xamarin#13]
**Describe the bug**
When I receive a push notification via Azure NotificationHub on iOS, the app crashes due to an System.InvalidCastException which happens inside the MSNotificationHubMessage class. Inside this class you cast the UserInfo from the push notification from a NSDictionary to a NSDictionary<NSString, NSString>. This seems to be wrong as the UserInfo does not only contain key-value pairs but also nested objects like:

`{
   "aps":{
      "alert":{
         "title":"My title",
         "body":"My body"
      },
   },
   "foo":"bar"
}`

***Exception or Stack Trace***
System.InvalidCastException: Unable to cast object of type 'Foundation.NSDictionary' to type 'Foundation.NSDictionary`2[[Foundation.NSString, Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065],[Foundation.NSString, Xamarin.iOS, Version=0.0.0.0, Culture=neutral…

**To Reproduce**
1. Send the push notification as mentioned above via Azure NotificationHub
2. Check the DidReceivePushNotification inside the iOS implementation of MSNotificationHubDelegate
3. Content of the NotificationHubMessage.UserInfo does not exist due to the CastException.

***Code Snippet***

`public override void DidReceivePushNotification(MSNotificationHub notificationHub, MSNotificationHubMessage message)
{
 OnNotificationMessageReceivedAction?.Invoke(message);
 }` 

UserInfo of MSNotificationHubMessage shows a CastException.

**Expected behavior**
Simply not cast it to a NSDictionary<NSString, NSString> but only to NSDictionary inside your wrapper implementation: 
* https://github.com/Azure/azure-notificationhubs-xamarin/blob/main/src/bindings/iOS/Xamarin.Azure.NotificationHubs.iOS/ApiDefinition.cs
* https://github.com/Azure/azure-notificationhubs-ios/blob/main/WindowsAzureMessaging/WindowsAzureMessaging/Model/MSNotificationHubMessage.m

**Setup (please complete the following information):**
 - OS: iOS 13.4
 - IDE : Visual Studio 2019 for Mac
 - Xamarin.Azure.NotificationHubs.iOS 3.1.0

**Comment by SergTomcat** [comment]
Have exatcly the same problem. It completely inhibits payload reading, and there's no way to access original payload for any workaround.
@RST90 provided simple and logical solution.

**Comment by mpodwysocki** [comment]
@SergTomcat Fixing as per 3.1.2 NuGet release which should be out soon, see https://github.com/xamarin/XamarinComponents/pull/1015
