### ISSUE TITLE
[FEATURE REQ] Target monoandroid10.0

### ISSUE THREAD

**Issue by adambarath** [Azure/azure-notificationhubs-xamarin#14]
It would be nice to bump build target to monoandroid10.0 and also use the AndroidX packages.

I think a the solution is add the monoandroid10.0 to the csproj and add reference to Xamarin.AndroidX.Migration nuget, too. I'm not sure, but probably it'll not necessary to create a new release from https://github.com/Azure/azure-notificationhubs-android , because AndroidX.Migration would handle AndroidX part of the build process.

- [X ] Description Added
- [ X] Expected solution specified

**Comment by jbtamaresgit** [comment]
Any updates for this? Apparently I am having an issue with Android10 for not receiving a push notification when I migrated to the latest packages for both androidX, firebase, and googleplayservices.

**Comment by marstr** [comment]
Fixed in https://github.com/Azure/azure-notificationhubs-xamarin/pull/15
