### ISSUE TITLE
[BUG] Android PlatformInitialize Method doesn't invoke Start

### ISSUE THREAD

**Issue by marstr** [Azure/azure-notificationhubs-xamarin#24]
This method should call `AndroidNotificationHub.Start(...)` but it doesn't:

https://github.com/Azure/azure-notificationhubs-xamarin/blob/5a6ead0dce88fc0cab389e7b28e57effdee070d5/src/Microsoft.Azure.NotificationHubs.Client/NotificationHub.android.cs#L93-L99

**Comment by mpodwysocki** [comment]
Closed as per #28
