### ISSUE TITLE
[BUG][Android] Installation fails

### ISSUE THREAD

**Issue by adambarath** [Azure/azure-notificationhubs-xamarin#25]
**Describe the bug**
Not regeristered itself as the documentation described, installation fails.. I call NotificationHub.Start(connString, hubName); after FirebaseMessagingService.OnNewToken is called by OS.

***Exception or Stack Trace***
InstallationSaveFailed Exception is:
`<Error><Code>400</Code><Detail>Installation validation failed with following error(s):&#xD;
'PushChannel' is required.&#xD;
Value cannot be null.&#xD;
Parameter name: gcmRegistrationId..TrackingId:8147d573-309e-4180-8ee0-a6bc9a068cf7_G20,TimeStamp:11/2/2020 8:06:38 AM</Detail></Error>`

**To Reproduce**
```
                Microsoft.Azure.NotificationHubs.Client.NotificationHub.InstallationSaved += (sender, e) => { };
                Microsoft.Azure.NotificationHubs.Client.NotificationHub.InstallationSaveFailed += (sender, e) => { };

                Microsoft.Azure.NotificationHubs.Client.NotificationHub.Start(connString, hubName);
```

**Expected behavior**
The API automatically handles using the Installation API for you once you have called the NotificationHub.Start method. 

**Screenshots**

**Setup (please complete the following information):**
Microsoft Visual Studio Enterprise 2019
Version 16.7.5
VisualStudio.16.Release/16.7.5+30523.141
Microsoft .NET Framework
Version 4.8.04084

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Xamarin.iOS and Xamarin.Mac SDK   14.0.0.0 (7ec3751a1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Additional context**
InstallationSaveFailed event is getting called all the times..

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by marstr** [comment]
Sorry you're running into trouble, @adambarath. We're aware of a race condition that may be causing some noise at initialization time, but that should resolve itself quickly. When you encounter this exception, is it a persistent problem or does it resolve itself after a few seconds?

If it is persistent, do you know that Firebase has finished initializing because you see a log entry, or because you have a second Firebase service receiving the event?

**Comment by adambarath** [comment]
It's persistent. 

This is my original implementation, so this code works well, tested, in production:
```
    [Service]
    [IntentFilter(new[] { "com.google.firebase.MESSAGING_EVENT" })]
    [IntentFilter(new[] { "com.google.firebase.INSTANCE_ID_EVENT" })]
    public class CustomFirebaseMessagingService : FirebaseMessagingService
    {
        private WindowsAzure.Messaging.NotificationHub hub;

        public override void OnNewToken(string token)
        {
            base.OnNewToken(token);

            // Register with Notification Hubs
            hub = new WindowsAzure.Messaging.NotificationHub(notificationHubName, connectionString, this);

            var regID = hub.Register(token, new string[0]{ }).RegistrationId;
            Log.Debug(TAG, $"Successful registration of ID {regID}");
        }
    }
```

BUT this is got that failure and run into InstallationSaveFailed always.
```
        public override void OnNewToken(string token)
        {
            base.OnNewToken(token);

            // Register with Notification Hubs
            NotificationHub.NotificationMessageReceived += (sender, e) => { };
            NotificationHub.InstallationSaved += (sender, e) => { };
            NotificationHub.InstallationSaveFailed += (sender, e) => { };

            NotificationHub.SetInstallationEnrichmentAdapter(new InstallationEnrichmentAdapter());
            NotificationHub.Start(new InstallationManagementDelegate());
            NotificationHub.Start(connectionString, notificationHubName);
        }
```

You pointed 'a second Firebase service receiving the event'. Is this a possible issue to have 2 firebase services?

**Comment by marstr** [comment]
I see - in the new namespace a `FirebaseMessagingService` is already created and running for you. If you look at your merged AndroidManifest.xml, there will be an entry for our `FirebaseReceiver`. Also, when using the new namespace, our code will take care of registering for you once you call `Start`, which should only need to be called once.

I have a few recommendations:
1. If you're not customizing the Installation record with an `EnrichmentAdapter`, feel free to skip that line.
1. You should only need one call to `NotificationHub.Start`, the last one with your connection string.
1.  Move that call to `Start` into your launch `Activity`, or wherever works for you that will be called once per application launch.
1. Delete your `FirebaseMessagingService`.

**Comment by adambarath** [comment]
So, do you mean the following part of the manifest?
````
    <service android:name="com.microsoft.windowsazure.messaging.notificationhubs.FirebaseReceiver" android:exported="false">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
        <action android:name="com.google.firebase.messaging.NEW_TOKEN" />
      </intent-filter>
    </service>
...
    <service android:name="crc6430ebb370297c4446.CustomFirebaseMessagingService">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
      <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
      </intent-filter>
    </service>
```

**Comment by marstr** [comment]
Yep - that's the relevant bit. To fix it, you can either suppress that addition of the new namespace's receiver and forego using any of the code there or remove yours.

Anyway, since this problem is understood and there's no action to take I'm going to close out this issue.

**Comment by adambarath** [comment]
Thank you for your help! 

I removed my FirebaseMessagingService and now it is works properly.
