### ISSUE TITLE
[BUG] Solution cannot be built on clone. 

### ISSUE THREAD

**Issue by wheelie33** [Azure/azure-notificationhubs-xamarin#38]
Clone the repo
open src/Microsoft.Azure.NotificationHubs.Client.sln

> The local source '/Users/jason/Downloads/azure-notificationhubs-xamarin-main/src/bindings/output' doesn't exist.

**Comment by tklempay** [comment]
I have the same error when I download the code and try to build it locally.  

For the heck of it, I created the missing ".../src/bindings/output" directory and reloaded the project.  

I now get the following error:
_Generating MSBuild file D:\Dev\azure-notificationhubs-xamarin-main\src\Microsoft.Azure.NotificationHubs.Client\obj\Microsoft.Azure.NotificationHubs.Client.csproj.nuget.g.targets.
Writing assets file to disk. Path: D:\Dev\azure-notificationhubs-xamarin-main\src\Microsoft.Azure.NotificationHubs.Client\obj\project.assets.json
Failed to restore D:\Dev\azure-notificationhubs-xamarin-main\src\Microsoft.Azure.NotificationHubs.Client\Microsoft.Azure.NotificationHubs.Client.csproj (in 2.89 sec).
NuGet package restore failed.  Please see Error List window for detailed warnings and errors._

Looking at the Error List window leads me to this (see attachment)
![build error-1](https://user-images.githubusercontent.com/44921765/103206194-4c42ba80-48c9-11eb-9681-89a70dc0b725.JPG)
:
_Error	NU1102	Unable to find package Xamarin.Azure.NotificationHubs.iOS with version (>= 3.1.2)
  - Found 10 version(s) in nuget.org [ Nearest version: 3.1.1 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in BuildOutput	Microsoft.Azure.NotificationHubs.Client	D:\Dev\azure-notificationhubs-xamarin-main\src\Microsoft.Azure.NotificationHubs.Client\Microsoft.Azure.NotificationHubs.Client.csproj	1_

**Comment by pablolop002** [comment]
Edit Microsoft.Azure.NotificationHubs.Client.csproj on line 46 and specify Xamarin.Azure.NotificationHubs.iOS version to 3.1.1, reload the project and then you can compile. The 3.1.2 isn't available on nugget.

**Comment by Phenek** [comment]
#95

**Comment by mpodwysocki** [comment]
Closing as per #95
