### ISSUE TITLE
How do I serialize the iOS NSData deviceToken to perform backend installation on a non Azure WebApi?

### ISSUE THREAD

**Issue by ederbond** [Azure/azure-notificationhubs-xamarin#5]
Using Xamarin.iOS, how do I correctly serialize the native iOS push token to properly send it to my asp.net core backend server for further usage to create an Azure Notification Hubs installation on the backend server. My asp.net core backend server will not be running on Azure it will be on premise server.
Can you guys help-me? Cause the docs just says that it is possible but doesn't explain how anywere, nor does the samples of this github project.

**Comment by marstr** [comment]
@mpodwysocki, mind taking a look at this?

**Comment by mpodwysocki** [comment]
@ederbond using the `Xamarin.Azure.NotificationHubs.iOS` package, you can get the token using the `MSNotificationHub.GetPushChannel()` method which should give you the device token.
