### ISSUE TITLE
[BUG] Dependencies:  2 downgrades and 4 upgrades

### ISSUE THREAD

**Issue by Phenek** [Azure/azure-notificationhubs-xamarin#94]
**Is your feature request related to a problem? Please describe.**
Your solution does not compile...
````
Xamarin.Azure.NotificationHubs.iOS Version="3.1.2" //does not exist in public nuget
Xamarin.AndroidX.AppCompat Version="1.3.1.4" //has been unreferenced by nuget, a downgrade is required

Xamarin.Google.Android.DataTransport.TransportRuntime Version="3.0.1.1" //should be updated
Xamarin.Firebase.Messaging" Version="122.0.0.3 //should be updated
Xamarin.Google.Android.DataTransport.TransportBackendCct Version="3.0.0.1" //should be updated
Xamarin.GooglePlayServices.Iid Version="117.0.0.3" //should be updated
Xamarin.GooglePlayServices.Base Version="117.6.0.3"// should be updated
````

**Describe the solution you'd like**
Please maintain packages references.
And provide a public nuget on nuget.org!! 
As describe in your documentation. please :)

**Describe alternatives you've considered**
Making a fork, a custom nuget and a PR.

**Information Checklist**
- [x] Xamarin.forms
- [x] Xamarin.iOS
- [x] Xamarin.Android

**Comment by mpodwysocki** [comment]
Closing as per #95
